# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ryan/ptolemy_2019/Cpp_AI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ryan/ptolemy_2019/Cpp_AI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ryan/ptolemy_2019/Cpp_AI/CMakeFiles /home/ryan/ptolemy_2019/Cpp_AI//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ryan/ptolemy_2019/Cpp_AI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Cpp_AI

# Build rule for target.
Cpp_AI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Cpp_AI
.PHONY : Cpp_AI

# fast build rule for target.
Cpp_AI/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/build
.PHONY : Cpp_AI/fast

src/dwba/av18_potential.o: src/dwba/av18_potential.cpp.o
.PHONY : src/dwba/av18_potential.o

# target to build an object file
src/dwba/av18_potential.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/dwba/av18_potential.cpp.o
.PHONY : src/dwba/av18_potential.cpp.o

src/dwba/av18_potential.i: src/dwba/av18_potential.cpp.i
.PHONY : src/dwba/av18_potential.i

# target to preprocess a source file
src/dwba/av18_potential.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/dwba/av18_potential.cpp.i
.PHONY : src/dwba/av18_potential.cpp.i

src/dwba/av18_potential.s: src/dwba/av18_potential.cpp.s
.PHONY : src/dwba/av18_potential.s

# target to generate assembly for a file
src/dwba/av18_potential.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/dwba/av18_potential.cpp.s
.PHONY : src/dwba/av18_potential.cpp.s

src/dwba/dwba.o: src/dwba/dwba.cpp.o
.PHONY : src/dwba/dwba.o

# target to build an object file
src/dwba/dwba.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/dwba/dwba.cpp.o
.PHONY : src/dwba/dwba.cpp.o

src/dwba/dwba.i: src/dwba/dwba.cpp.i
.PHONY : src/dwba/dwba.i

# target to preprocess a source file
src/dwba/dwba.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/dwba/dwba.cpp.i
.PHONY : src/dwba/dwba.cpp.i

src/dwba/dwba.s: src/dwba/dwba.cpp.s
.PHONY : src/dwba/dwba.s

# target to generate assembly for a file
src/dwba/dwba.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/dwba/dwba.cpp.s
.PHONY : src/dwba/dwba.cpp.s

src/dwba/math_utils.o: src/dwba/math_utils.cpp.o
.PHONY : src/dwba/math_utils.o

# target to build an object file
src/dwba/math_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/dwba/math_utils.cpp.o
.PHONY : src/dwba/math_utils.cpp.o

src/dwba/math_utils.i: src/dwba/math_utils.cpp.i
.PHONY : src/dwba/math_utils.i

# target to preprocess a source file
src/dwba/math_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/dwba/math_utils.cpp.i
.PHONY : src/dwba/math_utils.cpp.i

src/dwba/math_utils.s: src/dwba/math_utils.cpp.s
.PHONY : src/dwba/math_utils.s

# target to generate assembly for a file
src/dwba/math_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/dwba/math_utils.cpp.s
.PHONY : src/dwba/math_utils.cpp.s

src/dwba/potential_eval.o: src/dwba/potential_eval.cpp.o
.PHONY : src/dwba/potential_eval.o

# target to build an object file
src/dwba/potential_eval.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/dwba/potential_eval.cpp.o
.PHONY : src/dwba/potential_eval.cpp.o

src/dwba/potential_eval.i: src/dwba/potential_eval.cpp.i
.PHONY : src/dwba/potential_eval.i

# target to preprocess a source file
src/dwba/potential_eval.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/dwba/potential_eval.cpp.i
.PHONY : src/dwba/potential_eval.cpp.i

src/dwba/potential_eval.s: src/dwba/potential_eval.cpp.s
.PHONY : src/dwba/potential_eval.s

# target to generate assembly for a file
src/dwba/potential_eval.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/dwba/potential_eval.cpp.s
.PHONY : src/dwba/potential_eval.cpp.s

src/dwba/rcwfn.o: src/dwba/rcwfn.cpp.o
.PHONY : src/dwba/rcwfn.o

# target to build an object file
src/dwba/rcwfn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/dwba/rcwfn.cpp.o
.PHONY : src/dwba/rcwfn.cpp.o

src/dwba/rcwfn.i: src/dwba/rcwfn.cpp.i
.PHONY : src/dwba/rcwfn.i

# target to preprocess a source file
src/dwba/rcwfn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/dwba/rcwfn.cpp.i
.PHONY : src/dwba/rcwfn.cpp.i

src/dwba/rcwfn.s: src/dwba/rcwfn.cpp.s
.PHONY : src/dwba/rcwfn.s

# target to generate assembly for a file
src/dwba/rcwfn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/dwba/rcwfn.cpp.s
.PHONY : src/dwba/rcwfn.cpp.s

src/input/InputGenerator.o: src/input/InputGenerator.cpp.o
.PHONY : src/input/InputGenerator.o

# target to build an object file
src/input/InputGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/input/InputGenerator.cpp.o
.PHONY : src/input/InputGenerator.cpp.o

src/input/InputGenerator.i: src/input/InputGenerator.cpp.i
.PHONY : src/input/InputGenerator.i

# target to preprocess a source file
src/input/InputGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/input/InputGenerator.cpp.i
.PHONY : src/input/InputGenerator.cpp.i

src/input/InputGenerator.s: src/input/InputGenerator.cpp.s
.PHONY : src/input/InputGenerator.s

# target to generate assembly for a file
src/input/InputGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/input/InputGenerator.cpp.s
.PHONY : src/input/InputGenerator.cpp.s

src/input/Isotope.o: src/input/Isotope.cpp.o
.PHONY : src/input/Isotope.o

# target to build an object file
src/input/Isotope.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/input/Isotope.cpp.o
.PHONY : src/input/Isotope.cpp.o

src/input/Isotope.i: src/input/Isotope.cpp.i
.PHONY : src/input/Isotope.i

# target to preprocess a source file
src/input/Isotope.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/input/Isotope.cpp.i
.PHONY : src/input/Isotope.cpp.i

src/input/Isotope.s: src/input/Isotope.cpp.s
.PHONY : src/input/Isotope.s

# target to generate assembly for a file
src/input/Isotope.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/input/Isotope.cpp.s
.PHONY : src/input/Isotope.cpp.s

src/input/Potentials.o: src/input/Potentials.cpp.o
.PHONY : src/input/Potentials.o

# target to build an object file
src/input/Potentials.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/input/Potentials.cpp.o
.PHONY : src/input/Potentials.cpp.o

src/input/Potentials.i: src/input/Potentials.cpp.i
.PHONY : src/input/Potentials.i

# target to preprocess a source file
src/input/Potentials.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/input/Potentials.cpp.i
.PHONY : src/input/Potentials.cpp.i

src/input/Potentials.s: src/input/Potentials.cpp.s
.PHONY : src/input/Potentials.s

# target to generate assembly for a file
src/input/Potentials.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/input/Potentials.cpp.s
.PHONY : src/input/Potentials.cpp.s

src/input/PtolemyParser.o: src/input/PtolemyParser.cpp.o
.PHONY : src/input/PtolemyParser.o

# target to build an object file
src/input/PtolemyParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/input/PtolemyParser.cpp.o
.PHONY : src/input/PtolemyParser.cpp.o

src/input/PtolemyParser.i: src/input/PtolemyParser.cpp.i
.PHONY : src/input/PtolemyParser.i

# target to preprocess a source file
src/input/PtolemyParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/input/PtolemyParser.cpp.i
.PHONY : src/input/PtolemyParser.cpp.i

src/input/PtolemyParser.s: src/input/PtolemyParser.cpp.s
.PHONY : src/input/PtolemyParser.s

# target to generate assembly for a file
src/input/PtolemyParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/input/PtolemyParser.cpp.s
.PHONY : src/input/PtolemyParser.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cpp_AI.dir/build.make CMakeFiles/Cpp_AI.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Cpp_AI"
	@echo "... src/dwba/av18_potential.o"
	@echo "... src/dwba/av18_potential.i"
	@echo "... src/dwba/av18_potential.s"
	@echo "... src/dwba/dwba.o"
	@echo "... src/dwba/dwba.i"
	@echo "... src/dwba/dwba.s"
	@echo "... src/dwba/math_utils.o"
	@echo "... src/dwba/math_utils.i"
	@echo "... src/dwba/math_utils.s"
	@echo "... src/dwba/potential_eval.o"
	@echo "... src/dwba/potential_eval.i"
	@echo "... src/dwba/potential_eval.s"
	@echo "... src/dwba/rcwfn.o"
	@echo "... src/dwba/rcwfn.i"
	@echo "... src/dwba/rcwfn.s"
	@echo "... src/input/InputGenerator.o"
	@echo "... src/input/InputGenerator.i"
	@echo "... src/input/InputGenerator.s"
	@echo "... src/input/Isotope.o"
	@echo "... src/input/Isotope.i"
	@echo "... src/input/Isotope.s"
	@echo "... src/input/Potentials.o"
	@echo "... src/input/Potentials.i"
	@echo "... src/input/Potentials.s"
	@echo "... src/input/PtolemyParser.o"
	@echo "... src/input/PtolemyParser.i"
	@echo "... src/input/PtolemyParser.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

